### ISSUE TITLE
"An error occured in an add-on"

### ISSUE THREAD

**Issue by nitriles007** [sobjornstad/AnkiLPCG#12]
Traceback (most recent call last):
  File "/Users/David/Library/Application Support/Anki2/addons/LPCG.py", line 170, in open_dialog
    dialog = LPCGDialog(aqt.mw)
  File "/Users/David/Library/Application Support/Anki2/addons/LPCG.py", line 44, in __init__
    self.form = lpcgform.Ui_Dialog()
AttributeError: 'module' object has no attribute 'Ui_Dialog'

**Comment by sobjornstad** [comment]
Hi nitriles007,

I appear to have made an error when I repackaged the old version of the add-on for Anki 2.0 this weekend. I believe I've fixed it now – please try deleting the add-on and then downloading it from AnkiWeb again and let me know how that goes.

**Comment by nitriles007** [comment]
Soren, 

 

Thank you for the quick reply! I reinstalled and it works now. Great app, I’m using it to memorize The Raven. 

 

- David
