### ISSUE TITLE
Setting more than one line to be clozed at a time

### ISSUE THREAD

**Issue by hugomarins** [sobjornstad/AnkiLPCG#15]
I want to give suggestion, beyond thanking you for this app.

Certain kinds of music and poem have too short lines, and it would be more efficient to recall them in groups (of two lines, for example) instead of creating a lot of cards recalling just a few word.

If you could set this possibility in you add-on, just as we can already choose the number of context lines, it would be great!

**Comment by sobjornstad** [comment]
I like this idea! I'll put it on the list.

**Comment by sobjornstad** [comment]
Related suggestion from Ben in a private email:

> In the "Import Lyrics/Poetry" tool, similar to the "lines of context"
option, a "lines to recite" option (with a max. of 6 lines?).
>
> So if, for example, this option is set to "2", the cards generated will
ask for two lines to be recited. During reviews this could be indicated
by two [...][...].
>
> It would be very nice, if it was possible to indicate a range, e.g.
"1-3", with the add-on creating 3 sets of cards, with 1, 2 and 3 lines
to recite, preferably tagging them respectively as LR1, LR2, LR3 or
something similar.
>
> Of course a "lines to recite" option (whether the more simple or the
more complex version) would need some thought on how to avoid duplicate
cards being generated at the end of the poem.

**Comment by sobjornstad** [comment]
Both of these use cases should be covered in the latest version 1.3.0. Let me know if there are any issues.
