### ISSUE TITLE
How to use “type” class?

### ISSUE THREAD

**Issue by purequant** [sobjornstad/AnkiLPCG#16]
Thanks for developing the awesome addon.
But if I want to write the line,like "type" class,how can i do that?

**Comment by sobjornstad** [comment]
Sorry, I don't quite understand what you're asking. Could you give an example?

**Comment by purequant** [comment]
Oh,sorry,my English is poor.
I want to use the “type” function,so I changed the template like this,but it can't work.
```
<div class="title">{{Title}} {{Sequence}}</div>

<br>

<div class="lines">
{{Context}}
<span class="cloze">{{type:Line}}</span>
</div>
```
![image](https://user-images.githubusercontent.com/26440503/65104164-1dba0c80-da03-11e9-8190-766ff3bfd2f6.png)
Is there any way to do this?

**Comment by sobjornstad** [comment]
Ah, that makes sense now.

[As described in the manual](https://apps.ankiweb.net/docs/manual.html#checking-your-answer), you have to have a field with `type:` on it on both the front *and* the back of your cards for this feature to work. In your example, you've only put it on the back, so Anki doesn't know where to put the field you type your answer into on the front of the card, and consequently there's nothing to compare the correct answer with.

On your front template, try replacing

```
<span class="cloze">[...]</span>
```

with

```
{{type:Line}}
```

Does that accomplish what you want? In a quick test, this seemed to work for me.

**Comment by purequant** [comment]
Oh,how stupid I am.It also can work in my computer,thank you very much.
