### ISSUE TITLE
Set related cards

### ISSUE THREAD

**Issue by Anthea3** [sobjornstad/AnkiLPCG#31]
Hi,

I wonder if it is possible to set related cards for one poem to bury related reviews.
E.g., the poem is divided into 4 pieces, A B C D. Sometimes I'll see B C ___ and A B ___ in a short time, reviewing the second card will be meaningless and may lead to a longer recall time in mistake.

**Comment by sobjornstad** [comment]
Unfortunately no – Anki does not provide any way to bury different notes that are related, and [it isn't practical to use multiple cards per note](https://ankilpcg.readthedocs.io/en/latest/technical.html#why-separate-notes) for LPCG.
