### ISSUE TITLE
Whitespaces and IOError

### ISSUE THREAD

**Issue by fabswt** [sobjornstad/AnkiLPCG#4]
Hello,

Using AnkiLPCG with Python 2.7. I can drag and drop the input file, specify the title and tags, however I would then end up with the following error:

	C:\Users\Fabien\Downloads\AnkiLPCG-master\AnkiLPCG-master>lpcg.py
	    Lyrics/Poetry Cloze Generator v0.9.0
	    Copyright 2013 Soren Bjornstad; see COPYING for details.

	    Input File: Drag and drop the input file you wish to use onto this window.
	    Title:      This will be used to prompt you for the first line of the text.
	    Tags:       This will be fed to Anki as the Tags field of each card.

	    For further help, see the README.

	Input File: "D:\Dropbox\LANGUAGES\EN American English\English Pronunciation\Mode
	ls\Poems\Fire and Ice.txt"
	Title: Fire and Ice
	Tags (optional): FireAndIce
	Traceback (most recent call last):
	  File "C:\Users\Fabien\Downloads\AnkiLPCG-master\AnkiLPCG-master\lpcg.py", line
	 163, in <module>
	    main()
	  File "C:\Users\Fabien\Downloads\AnkiLPCG-master\AnkiLPCG-master\lpcg.py", line
	 112, in main
	    lyrics_file = open(input_file)
	IOError: [Errno 22] invalid mode ('r') or filename: '"D:\\Dropbox\\LANGUAGES\\EN
	 American English\\English Pronunciation\\Models\\Poems\\Fire and Ice.txt"'

I've fixed it by removing whitespaces from the input file's name and by moving it to a different directory. 

I would suggest either automatically adding double-quotes around the path or putting a warning about paths inside of the readme.

I hope it helps somewhat. 

By the way, thanks for the script, I've started playing with some poems I want to commit to memory and this is great stuff!

Fabien

**Comment by sobjornstad** [comment]
This situation is irrelevant in 1.0., so whatever it was, it should be okay now. :-)
